### ISSUE TITLE
AccountMapper两点问题

### ISSUE THREAD

**Issue by imuge** [QOSGroup/qbase#12]
1.用accountMapper保存账户信息，保存时带有前缀，abci query处需要处理
2.方法不够用时无法注册自己的accountMapper
@TokenxyWZY

**Comment by kauchy** [comment]
account保存前缀通过account通用方法可以屏蔽，对我总是通过该方法生成对应key @blackpainter

**Comment by blackpainter** [comment]
前缀可以用于IterateAccounts，批量获取全部为特定前缀的account，在query request的$subpath为"subspace"时也有用到。当然数据量过大时可能有内存占用问题，我们打算后面加上限制条件来限制数据集大小；
自己定义的account可参见qosaccount_test测试用例，通过继承BaseAccount，使用反射来使用AccountMapper
