### ISSUE TITLE
keys  export/import

### ISSUE THREAD

**Issue by imuge** [QOSGroup/qbase#188]
导出密钥包含名称、地址、公私钥信息，导入密钥文件仅能包含私钥，使用中发现几处不便：
- 导出信息是否可以直接写文件，免去手动复制保存
- 导出信息无法用于直接用户导入
- 是否需要增加直接通过传入私钥导入方式

**Comment by blackpainter** [comment]
可以参照parity导出的账户信息格式，包含用账户密码加密的私钥
https://wiki.parity.io/Backing-up-&-Restoring
这个文件在metamask中也可导入（跨钱包），导入时需要输入parity账户密码解密

**Comment by TokenxyWZY** [comment]
fix #
