### ISSUE TITLE
validateTxStdUserSignatureAndNonce nil

### ISSUE THREAD

**Issue by imuge** [QOSGroup/qbase#27]
https://github.com/QOSGroup/qbase/blob/master/baseabci/baseapp.go#L403
下面这块代码是不是有问题？
`
signerAccount := make([]account.Account, len(signers))
for _, addr := range signers {
	acc := accounMapper.GetAccount(addr)
	if acc == nil {
		acc = accounMapper.NewAccountWithAddress(addr)
	}
	signerAccount = append(signerAccount, acc)
}
`
make时创建了len(signers)个，后面用的append，也就是前面len(signers)都会是nil @TokenxyWZY

**Comment by TokenxyWZY** [comment]
@imuge 已修改 :+1:
