### ISSUE TITLE
对交易和交易序号查询key的组装希望能提供公共方法支持

### ISSUE THREAD

**Issue by snowdiceX** [QOSGroup/qbase#56]
目前对交易及交易序号查询接口依赖较大，交易和交易序号查询key值的组装规则有可能变化较大，希望提供公共方法支持，直接通过参数可以生成所需的查询key值。

**Comment by kauchy** [comment]
所有的存储key都需要在相关mapper中增加生成方法，命名规则保持一致
@TokenxyWZY @imuge @blackpainter @MicroWave001

**Comment by imuge** [comment]
在相应mapper中，方法命名规则 BuildXxxKey @snowdiceX

**Comment by kauchy** [comment]
@QOSGroup/public-team
