### ISSUE TITLE
account中nonce,qcp中sequence规则问题

### ISSUE THREAD

**Issue by kauchy** [QOSGroup/qbase#68]
account中nonce作用为区分账户account交易序号，qcp中sequence中用来区分qcp交易in/out序号。

当前：
nonce规则为当前值为account下一笔交易的序号，交易签名时直接使用该值。
sequence规则为已经产生和接收到的qcp序号，中继查询到之后加1处理。

是否需要将nonce规则也修改为当前已经接收到交易数量，交易签名时加1填充??

**Comment by kauchy** [comment]
@QOSGroup/public-team

**Comment by bshang** [comment]
1. sequence为啥要加1？
2. sequence还对接收tx进行递增？

**Comment by blackpainter** [comment]
验签后+1比较符合一般的思维习惯……一个感觉不一定对

**Comment by kauchy** [comment]
fix #71。qcp中sequence和account中nonce都代表当前已经处理的tx序号，下一笔交易都加1。初始值都为0，提交时都从1开始。
@QOSGroup/public-team
