### ISSUE TITLE
一般的查询就不要写日志了吧

### ISSUE THREAD

**Issue by tedyyan** [QOSGroup/qbase#92]
I[11-06|06:43:29.268] ABCIQuery                                    module=rpc path=/store/qcp/key data=74782F6F75742F716F732D746573742F38 result="key:\"tx/out/qos-test/8\" proof:\"\\244\\002\\n\\021\\n\\010qstarskv\\022\\005\\n\\003\\010\\362\\006\\n\\\"\\n\\003qcp\\022\\033\\n\\031\\010\\362\\006\\022\\024\\n>\\230\\374\\r\\350\\032Y\\004\\233\\211\\240\\346\\030\\272b\\226\\006\\255\\333\\n\\014\\n\\003acc\\022\\005\\n\\003\\010\\362\\006\\n+\\n\\014qstarsResult\\022\\033\\n\\031\\010\\362\\006\\022\\0244\\033\\335\\345&\\210T\\252\\304!\\202\\212\\220\\0019\\240\\3755\\016-\\022\\003qcp\\032\\252\\001\\n\\035\\010\\010\\020\\024\\030\\310\\006\\\"\\024\\314\\207u-X\\211\\0344xN\\353\\204\\274\\002x\\353w\\354\\272|\\n\\035\\010\\006\\020\\014\\030\\302\\006\\\"\\024-\\212\\020uJ\\020\\032\\035\\213\\336\\376\\337\\005Y\\264\\010P\\016\\271\\212\\n\\035\\010\\004\\020\\010\\030\\302\\006\\\"\\024D\\363U\\022\\324*UW\\035\\364\\243p--w\\301W\\373\\\\\\027\\n\\035\\010\\002\\020\\004\\030\\302\\006\\\"\\024e8'\\231\\270\\253\\177\\344d\\222@\\233\\260\\217\\237x\\271\\377R}\\032,\\n\\021tx/out/qos-test/7\\022\\024\\315\\023\\363\\272\\037\\227p\\312X\\207Kc\\t\\235/\\317\\243\\006\\360\\242\\030\\302\\006\" height:441 "
I[11-06|06:43:29.269] HTTPJSONRPC                                  module=rpc-server method=abci_query args="[/store/qcp/key <common.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*core_types.ResultABCIQuery Value> <error Value>]"
I[11-06|06:43:29.269] Served RPC HTTP response                     module=rpc-server method=POST url=/ status=200 duration=0 remoteAddr=192.168.1.226:44706
I[11-06|06:43:29.271] ABCIQuery                                    module=rpc path=/store/qcp/key data=74782F6F75742F716F732D746573742F38 result="key:\"tx/out/qos-test/8\" proof:\"\\244\\002\\n\\021\\n\\010qstarskv\\022\\005\\n\\003\\010\\362\\006\\n\\\"\\n\\003qcp\\022\\033\\n\\031\\010\\362\\006\\022\\024\\n>\\230\\374\\r\\350\\032Y\\004\\233\\211\\240\\346\\030\\272b\\226\\006\\255\\333\\n\\014\\n\\003acc\\022\\005\\n\\003\\010\\362\\006\\n+\\n\\014qstarsResult\\022\\033\\n\\031\\010\\362\\006\\022\\0244\\033\\335\\345&\\210T\\252\\304!\\202\\212\\220\\0019\\240\\3755\\016-\\022\\003qcp\\032\\252\\001\\n\\035\\010\\010\\020\\024\\030\\310\\006\\\"\\024\\314\\207u-X\\211\\0344xN\\353\\204\\274\\002x\\353w\\354\\272|\\n\\035\\010\\006\\020\\014\\030\\302\\006\\\"\\024-\\212\\020uJ\\020\\032\\035\\213\\336\\376\\337\\005Y\\264\\010P\\016\\271\\212\\n\\035\\010\\004\\020\\010\\030\\302\\006\\\"\\024D\\363U\\022\\324*UW\\035\\364\\243p--w\\301W\\373\\\\\\027\\n\\035\\010\\002\\020\\004\\030\\302\\006\\\"\\024e8'\\231\\270\\253\\177\\344d\\222@\\233\\260\\217\\237x\\271\\377R}\\032,\\n\\021tx/out/qos-test/7\\022\\024\\315\\023\\363\\272\\037\\227p\\312X\\207Kc\\t\\235/\\317\\243\\006\\360\\242\\030\\302\\006\" height:441 "
I[11-06|06:43:29.272] HTTPJSONRPC                                  module=rpc-server method=abci_query args="[/store/qcp/key <common.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*core_types.ResultABCIQuery Value> <error Value>]"
I[11-06|06:43:29.272] Served RPC HTTP response                     module=rpc-server method=POST url=/ status=200 duration=0 remoteAddr=192.168.1.226:44708
I[11-06|06:43:30.268] ABCIQuery                                    module=rpc path=/store/qcp/key data=74782F6F75742F716F732D746573742F38 result="key:\"tx/out/qos-test/8\" proof:\"\\244\\002\\n\\021\\n\\010qstarskv\\022\\005\\n\\003\\010\\362\\006\\n\\\"\\n\\003qcp\\022\\033\\n\\031\\010\\362\\006\\022\\024\\n>\\230\\374\\r\\350\\032Y\\004\\233\\211\\240\\346\\030\\272b\\226\\006\\255\\333\\n\\014\\n\\003acc\\022\\005\\n\\003\\010\\362\\006\\n+\\n\\014qstarsResult\\022\\033\\n\\031\\010\\362\\006\\022\\0244\\033\\335\\345&\\210T\\252\\304!\\202\\212\\220\\0019\\240\\3755\\016-\\022\\003qcp\\032\\252\\001\\n\\035\\010\\010\\020\\024\\030\\310\\006\\\"\\024\\314\\207u-X\\211\\0344xN\\353\\204\\274\\002x\\353w\\354\\272|\\n\\035\\010\\006\\020\\014\\030\\302\\006\\\"\\024-\\212\\020uJ\\020\\032\\035\\213\\336\\376\\337\\005Y\\264\\010P\\016\\271\\212\\n\\035\\010\\004\\020\\010\\030\\302\\006\\\"\\024D\\363U\\022\\324*UW\\035\\364\\243p--w\\301W\\373\\\\\\027\\n\\035\\010\\002\\020\\004\\030\\302\\006\\\"\\024e8'\\231\\270\\253\\177\\344d\\222@\\233\\260\\217\\237x\\271\\377R}\\032,\\n\\021tx/out/qos-test/7\\022\\024\\315\\023\\363\\272\\037\\227p\\312X\\207Kc\\t\\235/\\317\\243\\006\\360\\242\\030\\302\\006\" height:441 "
I[11-06|06:43:30.268] HTTPJSONRPC                                  module=rpc-server method=abci_query args="[/store/qcp/key <common.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*core_types.ResultABCIQuery Value> <error Value>]"
I[11-06|06:43:30.268] Served RPC HTTP response                     module=rpc-server method=POST url=/ status=200 duration=0 remoteAddr=192.168.1.226:44708
I[11-06|06:43:30.271] ABCIQuery                                    module=rpc path=/store/qcp/key data=74782F6F75742F716F732D746573742F38 result="key:\"tx/out/qos-test/8\" proof:\"\\244\\002\\n\\021\\n\\010qstarskv\\022\\005\\n\\003\\010\\362\\006\\n\\\"\\n\\003qcp\\022\\033\\n\\031\\010\\362\\006\\022\\024\\n>\\230\\374\\r\\350\\032Y\\004\\233\\211\\240\\346\\030\\272b\\226\\006\\255\\333\\n\\014\\n\\003acc\\022\\005\\n\\003\\010\\362\\006\\n+\\n\\014qstarsResult\\022\\033\\n\\031\\010\\362\\006\\022\\0244\\033\\335\\345&\\210T\\252\\304!\\202\\212\\220\\0019\\240\\3755\\016-\\022\\003qcp\\032\\252\\001\\n\\035\\010\\010\\020\\024\\030\\310\\006\\\"\\024\\314\\207u-X\\211\\0344xN\\353\\204\\274\\002x\\353w\\354\\272|\\n\\035\\010\\006\\020\\014\\030\\302\\006\\\"\\024-\\212\\020uJ\\020\\032\\035\\213\\336\\376\\337\\005Y\\264\\010P\\016\\271\\212\\n\\035\\010\\004\\020\\010\\030\\302\\006\\\"\\024D\\363U\\022\\324*UW\\035\\364\\243p--w\\301W\\373\\\\\\027\\n\\035\\010\\002\\020\\004\\030\\302\\006\\\"\\024e8'\\231\\270\\253\\177\\344d\\222@\\233\\260\\217\\237x\\271\\377R}\\032,\\n\\021tx/out/qos-test/7\\022\\024\\315\\023\\363\\272\\037\\227p\\312X\\207Kc\\t\\235/\\317\\243\\006\\360\\242\\030\\302\\006\" height:441 "
I[11-06|06:43:30.271] HTTPJSONRPC                                  module=rpc-server method=abci_query args="[/store/qcp/key <common.HexBytes Value> <int64 Value> <bool Value>]" returns="[<*core_types.ResultABCIQuery Value> <error Value>]"
I[11-06|06:43:30.272] Served RPC HTTP response                     module=rpc-server method=POST url=/ status=200 duration=0 remoteAddr=192.168.1.226:44710

**Comment by kauchy** [comment]
这是tendermint标准日志

**Comment by kauchy** [comment]
将log_level对应模块日志级别调高就行了，rpc-server:error @tedyyan
